# -*- coding: utf-8 -*-
"""EDA_progetto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dEXramn0iCsedaXne9Wja457fIumM22K
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

palette_colors = ["#e8dacd", "#a0a98a", "#d19798", "#a9a186", "#a75f44", "#d19798"]

products = pd.read_csv('product_info.csv')
reviews = pd.read_csv('reviews_0-250.csv')

print("PRODUCTS DATASET")
print(f"\nShape: {products.shape}")
print(f"\nColonne:{products.columns.tolist()}")
print(f"\nPrime righe:")
print(products.head())

print("\nREVIEWS DATASET")
print(f"\nShape: {reviews.shape}")
print(f"\nColonne:{reviews.columns.tolist()}")
print(f"\nPrime righe:")
print(reviews.head())

# DISTRIBUZIONE DEL TARGET (is_recommended)

# conteggio assoluto
class_counts = reviews['is_recommended'].value_counts()
print("Conteggi classi:\n", class_counts)

# percentuali
class_percent = reviews['is_recommended'].value_counts(normalize=True) * 100
print("\nPercentuali classi:\n", class_percent)

# DISTRIBUZIONE FEATURES UTENTE

# Feature skin_type

skin_type_counts = reviews['skin_type'].value_counts()
print("Conteggi skin_type:\n", skin_type_counts)
skin_type_percent = reviews['skin_type'].value_counts(normalize=True, dropna=False) * 100
print("\nPercentuali skin_type:\n", skin_type_percent)

sns.countplot(
    data=reviews,
    x='skin_type',
    order=skin_type_counts.index,
    hue='skin_type',
    palette=palette_colors
)
plt.title("Distribuzione del tipo di pelle")
plt.xlabel("Tipo di pelle")
plt.ylabel("Conteggio")
plt.show()

# Feature skin_tone

skin_tone_counts = reviews['skin_tone'].value_counts()
print("Conteggi skin_tone:\n", skin_tone_counts)
skin_tone_percent = reviews['skin_tone'].value_counts(normalize=True, dropna=False) * 100
print("\nPercentuali skin_tone:\n", skin_tone_percent)

sns.countplot(
    data=reviews,
    x='skin_tone',
    order=skin_tone_counts.index,
    hue='skin_tone',
    palette=palette_colors,
    dodge=False         # evita duplicazione barre
)
plt.title("Distribuzione del tono della pelle")
plt.xlabel("Tono della pelle")
plt.ylabel("Conteggio")
plt.xticks(rotation=45, ha='right')  # ruota le etichette e le allinea a destra
plt.tight_layout()    # adatta automaticamente margini e spazio
plt.show()

# DISTRIBUZIONE FEATURES PRODOTTO

# Feature rating (rating medio per prodotto, NON delle singole recensioni)
plt.figure(figsize=(8,5))
sns.histplot(
    products['rating'].dropna(),
    bins=20,  # in quante barre viene suddiviso l’istogramma
    color="#d7af9e"
    )
plt.title("Distribuzione dei rating medi dei prodotti")
plt.xlabel("Rating")
plt.ylabel("Conteggio")
plt.tight_layout()
plt.show()

# Conteggio dei rating (per fasce)
bins = [0,1,2,3,4,5]
rating_binned = pd.cut(products['rating'], bins).value_counts().sort_index()
print(rating_binned)

# Feature reviews
plt.figure(figsize=(8,5))
sns.histplot(
    products['reviews'].dropna(),
    # bins=20,  # in quante barre viene suddiviso l’istogramma
    bins = [0,10,50,100,200,500,1000,5000,10000,25000],
    color="#d7af9e"
    )
plt.title("Distribuzione del numero di recensioni per prodotto")
plt.xlabel("Reviews")
plt.ylabel("Conteggio")
plt.tight_layout()
plt.show()

# Conteggio reviews (per fasce)
bins = [0,10,50,100,200,500,1000,5000,10000,25000]
reviews_binned = pd.cut(products['reviews'], bins).value_counts().sort_index()
print()
print(reviews_binned)

# MISSING VALUES

# Reviews Dataset

# numero di missing per colonna
missing_reviews = reviews.isnull().sum()
# percentuali
missing_reviews_percent = (missing_reviews / len(reviews)) * 100
# DataFrame ordinato
missing_reviews_df = pd.DataFrame({
    'missing_count': missing_reviews,
    'missing_percent': missing_reviews_percent
}).sort_values(by='missing_percent', ascending=False)
print("Missing values in reviews:")
print(missing_reviews_df)
print()

# Products Dataset

# numero di missing per colonna
missing_products = products.isnull().sum()
# percentuali
missing_products_percent = (missing_products / len(products)) * 100
# DataFrame ordinato
missing_products_df = pd.DataFrame({
    'missing_count': missing_products,
    'missing_percent': missing_products_percent
}).sort_values(by='missing_percent', ascending=False)
print("Missing values in products:")
print(missing_products_df)

# OUTLIERS

# Products Dataset

numeric_cols = [
    "loves_count",
    "rating",
    "reviews",
    "price_usd",
]

for col in numeric_cols:
    plt.figure(figsize=(8, 2.5))
    sns.boxplot(
        x=products[col],
        color="lightpink"
        )
    plt.title(f"Boxplot di {col}", fontsize=12)
    plt.xlabel(col)
    plt.tight_layout()
    plt.show()
    print(f"--- {col} ---")
    print(products[col].describe())
    print()

# Reviews Dataset

plt.figure(figsize=(8, 2.5))
sns.boxplot(
    x=reviews["rating"],
    color="lightpink"
    )
plt.title(f"Boxplot di rating (avg)", fontsize=12)
plt.xlabel("rating")
plt.tight_layout()
plt.show()

print(f"--- rating di Reviews ---")
print(reviews["rating"].describe())

# CONTROLLO CHIAVE DI JOIN (product_id)

print(f"Product_id in reviews:")
print(f"  - Valori unici: {reviews['product_id'].nunique():,}")
print(f"  - Missing: {reviews['product_id'].isna().sum()}")

print(f"\nProduct_id in products:")
print(f"  - Valori unici: {products['product_id'].nunique():,}")
print(f"  - Missing: {products['product_id'].isna().sum()}")

# quanti product_id di reviews esistono anche in products?
products_in_reviews = reviews['product_id'].unique()
products_in_catalog = products['product_id'].unique()

match_count = len(set(products_in_reviews) & set(products_in_catalog)) # restituisce solo gli elementi presenti in entrambi i set
total_in_reviews = len(products_in_reviews)

print(f"\nMatch tra dataset:")
print(f"  - Prodotti unici in reviews: {total_in_reviews:,}")
print(f"  - Prodotti trovati in products: {match_count:,} ({match_count/total_in_reviews*100}%)")

if match_count < total_in_reviews:
    missing_products = total_in_reviews - match_count
    print(f" {missing_products} prodotti in reviews NON trovati")

# RIMOZIONE FEATURES NON RILEVANTI

# Reviews Dataset

reviews_drop_cols = [
    'Unnamed: 0', 'author_id', 'review_text', 'review_title', 'submission_time',
    'helpfulness', 'hair_color', 'eye_color',
    'total_feedback_count', 'total_pos_feedback_count', 'total_neg_feedback_count',
    'product_name', 'brand_name'
]

reviews_clean = reviews.drop(columns=reviews_drop_cols)

# rinomina colonne di reviews per evitare conflitti
reviews_clean = reviews_clean.rename(columns={
    'rating': 'user_rating',        # rating assegnato dall'utente (singola recensione)
    'price_usd': 'review_price_usd' # prezzo del prodotto al momento della recensione
})

print("Reviews Dataset dopo drop:", reviews_clean.shape)
print(reviews_clean.columns)

# Products Dataset

products_drop_cols = [
    'sale_price_usd', 'value_price_usd',
    'variation_desc', 'variation_type', 'variation_value',
    'child_max_price', 'child_min_price', 'child_count',
    'size',
    'limited_edition', 'new', 'online_only', 'out_of_stock', 'sephora_exclusive',
    'brand_id', 'product_name'
]

products_clean = products.drop(columns=products_drop_cols)

# rinomina colonne di products per evitare conflitti
products_clean = products_clean.rename(columns={
    'rating': 'avg_product_rating', # rating medio del prodotto
    'price_usd': 'product_price_usd', # prezzo attuale del prodotto
    'reviews' : 'reviews_count' # numero di recensioni riguardo al prodotto
})

print("\nProducts dataset dopo drop:", products_clean.shape)
print(products_clean.columns)

# MERGE DATASET

df = pd.merge(
    reviews_clean,
    products_clean,
    on='product_id',
    how='inner',  # inner join
)

print(f"Shape dopo merge: {df.shape}")
print(df.columns)

# salvo il dataset dopo merge
df.to_csv('dataset_merged.csv', index=False)
files.download('dataset_merged.csv')