# -*- coding: utf-8 -*-
"""Modello_progetto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wCkNcXYjGT2ljpCFISTA9RS_Gx2AUv8t
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.metrics import roc_curve, auc

from imblearn.over_sampling import SMOTE

train = pd.read_csv('train1.csv')
val = pd.read_csv('val1.csv')
test = pd.read_csv('test1.csv')

print(f"Train Shape: {train.shape}")
print(f"\nPrime righe:")
print(train.head())

print(f"\nValidation Shape: {val.shape}")
print(f"\nPrime righe:")
print(val.head())

print(f"\nTest Shape: {test.shape}")
print(f"\nPrime righe:")
print(test.head())

# SEPARO IL TARGET DALLE FEATURE

X_train = train.drop(columns='is_recommended')
y_train = train['is_recommended']

X_val = val.drop(columns='is_recommended')
y_val = val['is_recommended']

X_test = test.drop(columns='is_recommended')
y_test = test['is_recommended']

# REGRESSIONE LOGISTICA

logreg = LogisticRegression(
    solver='liblinear',   # ottimizzatore, adatto a classif binaria con feature codificate, dataset medie dim
    class_weight='balanced',
    random_state=42       # seme per generatore numeri casuali, riproducibilità
)

# fit sul training set
logreg.fit(X_train, y_train)

# RANDOM FOREST

rf = RandomForestClassifier(
    n_estimators=100,       # 100 alberi: trade-off precisione-tempo
    max_depth=None,         # non limita profondità
    class_weight='balanced',
    random_state=42,
    n_jobs=-1               # usa tutti i core disponibili
)

# fit sul training set
rf.fit(X_train, y_train)

# VALUTAZIONE SUL VALUTATION SET (REGRESSIONE LOGISTICA E RANDOM FOREST)

models = {
    "Logistic Regression": logreg,
    "Random Forest": rf
}

for name, model in models.items():
    print(f"\n=== {name} ===")

    # predizioni sul validation set
    y_val_pred = model.predict(X_val)
    y_val_prob = model.predict_proba(X_val)[:, 1]  # probabilità classe positiva

    # metriche
    acc = accuracy_score(y_val, y_val_pred)
    prec = precision_score(y_val, y_val_pred)
    rec = recall_score(y_val, y_val_pred)
    f1 = f1_score(y_val, y_val_pred)
    roc = roc_auc_score(y_val, y_val_prob)
    cm = confusion_matrix(y_val, y_val_pred)

    print(f"Accuracy: {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall: {rec:.4f}")
    print(f"F1-score: {f1:.4f}")
    print(f"ROC AUC: {roc:.4f}")
    print("Confusion Matrix:")
    print(cm)

# SMOTE SUL TRAINING SET

X_train_x_smote = X_train.copy()
y_train_x_smote = y_train.copy()

smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train_x_smote, y_train_x_smote)

print(f"Shape DOPO SMOTE: {X_train_sm.shape}")

# check
y_train.value_counts(normalize=True)
y_train_sm.value_counts(normalize=True)

# RIADDESTRA REGRESSIONE LOGISTICA CON SMOTE

logreg_sm = LogisticRegression(
    solver='liblinear',
    class_weight=None,   # no 'balanced' con SMOTE
    random_state=42
)

logreg_sm.fit(X_train_sm, y_train_sm)

# BALANCED RANDOM FOREST

brf = BalancedRandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

brf.fit(X_train, y_train)

# VALUTAZIONE SUL VALUTATION (LR CON SMOTE E BRF)

models = {
    "Logistic Regression con SMOTE": logreg_sm,
    "Balanced Random Forest": brf
}

for name, model in models.items():
    print(f"\n=== {name} ===")

    # predizioni sul validation set
    y_val_pred = model.predict(X_val)
    y_val_prob = model.predict_proba(X_val)[:, 1]  # probabilità classe positiva

    # metriche
    acc = accuracy_score(y_val, y_val_pred)
    prec = precision_score(y_val, y_val_pred)
    rec = recall_score(y_val, y_val_pred)
    f1 = f1_score(y_val, y_val_pred)
    roc = roc_auc_score(y_val, y_val_prob)
    cm = confusion_matrix(y_val, y_val_pred)

    print(f"Accuracy: {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall: {rec:.4f}")
    print(f"F1-score: {f1:.4f}")
    print(f"ROC AUC: {roc:.4f}")
    print("Confusion Matrix:")
    print(cm)

# VALUTAZIONE LR SENZA SMOTE SUL TEST SET

y_test_pred = logreg.predict(X_test)
y_test_proba = logreg.predict_proba(X_test)[:,1]

print(f"\n=== LOGISTIC REGRESSION SUL TEST SET ===")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision:", precision_score(y_test, y_test_pred))
print("Recall:", recall_score(y_test, y_test_pred))
print("F1-score:", f1_score(y_test, y_test_pred))
print("ROC AUC:", roc_auc_score(y_test, y_test_proba))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))

# CURVA ROC (LR)

# probabilità classe positiva
y_test_proba = logreg.predict_proba(X_test)[:, 1]

# calcolo ROC
fpr, tpr, thresholds = roc_curve(y_test, y_test_proba)
roc_auc = auc(fpr, tpr)

# plot
plt.figure(figsize=(7, 6))
plt.plot(fpr, tpr, label=f'Logistic Regression (AUC = {roc_auc:.3f})')
plt.plot([0, 1], [0, 1], 'k--', label='Random guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - Logistic Regression (Test Set)')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

# THRESHOLDS TUNING

# probabilità classe positiva sul validation set
y_val_prob = logreg.predict_proba(X_val)[:, 1]

# soglie da testare (da 0.1 a 0.85 con step 0.05)
thresholds = np.arange(0.1, 0.9, 0.05)

# ciclo sulle soglie
for t in thresholds:
    y_val_pred_t = (y_val_prob >= t).astype(int) # creo array di booleani: true se probabilità >= soglia
    print(
        f"T={t:.2f} | "
        f"Precision={precision_score(y_val, y_val_pred_t):.3f} | "
        f"Recall={recall_score(y_val, y_val_pred_t):.3f} | "
        f"F1 Score={f1_score(y_val, y_val_pred_t):.3f}"
    )

# APPLICA LA SOGLIA 0.20 SUL TEST SET

threshold = 0.20

# probabilità classe positiva sul test set
y_test_prob = logreg.predict_proba(X_test)[:, 1]

# applico soglia 0.20
y_test_pred = (y_test_prob >= threshold).astype(int) # array di booleani come prima

# metriche finali
print("Precision:", precision_score(y_test, y_test_pred))
print("Recall:", recall_score(y_test, y_test_pred))
print("F1:", f1_score(y_test, y_test_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_test_pred))