# -*- coding: utf-8 -*-
"""Preprocessing_progetto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OgWH0FTAX-WlFrJ-DkrMpZ9VDtcCkZVG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from google.colab import files

df = pd.read_csv('dataset_merged1.csv')

print(f"Shape: {df.shape}")
print(f"\nColonne:{df.columns.tolist()}")
print(f"\nPrime righe:")
print(df.head())

# INDIVIDUAZIONE MISSING VALUES

# numero di missing per colonna
missing_values = df.isnull().sum()
# percentuali
missing_values_percent = (missing_values / len(df)) * 100
# DataFrame ordinato
missing_df = pd.DataFrame({
    'missing_count': missing_values,
    'missing_percent': missing_values_percent
}).sort_values(by='missing_percent', ascending=False)
print(missing_df)

# GESTIONE MISSING VALUES

# rimozione righe con target (is_recommended) mancante
df = df.dropna(subset=["is_recommended"])

# imputazione skin_tone e skin_type (unknown)
df["skin_tone"] = df["skin_tone"].fillna("unknown")
df["skin_type"] = df["skin_type"].fillna("unknown")

# imputazione tertiary_category (not_specified)
df["tertiary_category"] = df["tertiary_category"].fillna("not_specified")

# imputazione highlights (no_highlights)
df["highlights"] = df["highlights"].fillna("no_highlights")

# imputazione ingredients "unknown"
df['ingredients'] = df['ingredients'].fillna('unknown')

# check
missing_after = df.isna().sum()
print(missing_after[missing_after > 0]) # filtro
print(f"Nuova Shape: {df.shape}")

# GESTIONE OUTLIERS (trasformazioni)

# feature loves_count

print(f"loves_count prima della trasformazione:")
print(f"  Range: [{df['loves_count'].min():.0f}, {df['loves_count'].max():.0f}]")
print(f"  Media: {df['loves_count'].mean():.0f}")
print(f"  Mediana: {df['loves_count'].median():.0f}")

df['loves_count_log'] = np.log1p(df['loves_count'])

print(f"\nloves_count dopo trasformazione LOG (feature loves_count_log):")
print(f"  Range: [{df['loves_count_log'].min():.2f}, {df['loves_count_log'].max():.2f}]")
print(f"  Media: {df['loves_count_log'].mean():.2f}")
print(f"  Mediana: {df['loves_count_log'].median():.2f}")

# feature reviews_count

print(f"\nreviews_count prima della trasformazione:")
print(f"  Range: [{df['reviews_count'].min():.0f}, {df['reviews_count'].max():.0f}]")
print(f"  Media: {df['reviews_count'].mean():.0f}")
print(f"  Mediana: {df['reviews_count'].median():.0f}")

df['reviews_count_log'] = np.log1p(df['reviews_count'])

print(f"\nreviews_count dopo trasformazione LOG (feature reviews_count_log):")
print(f"  Range: [{df['reviews_count_log'].min():.2f}, {df['reviews_count_log'].max():.2f}]")
print(f"  Media: {df['reviews_count_log'].mean():.2f}")
print(f"  Mediana: {df['reviews_count_log'].median():.2f}")

# ENCODING FEATURE CATEGORICHE

# feature skin_type

print(f"Distribuzione skin_type:");
df['skin_type'].value_counts()

skin_type_order = ['unknown', 'dry', 'normal', 'combination', 'oily']
df['skin_type_encoded'] = df['skin_type'].map({v:i for i,v in enumerate(skin_type_order)}) # da 0 a 4

print(f"\nDistribuzione skin_type DOPO encoding:")
df['skin_type_encoded'].value_counts()

# feature skin_tone

print(f"Distribuzione skin_tone:")
df['skin_tone'].value_counts()

# raggruppamento logico
skin_tone_mapping = {
    'porcelain': 'very_fair',
    'fair': 'very_fair',
    'fairLight': 'very_fair',

    'light': 'light',
    'lightMedium': 'light',

    'medium': 'medium',
    'olive': 'medium',

    'mediumTan': 'tan',
    'tan': 'tan',

    'deep': 'deep',
    'dark': 'deep',
    'rich': 'deep',
    'ebony': 'deep',

    'unknown': 'unknown',
    'notSureST': 'unknown',
}
df['skin_tone_grouped'] = df['skin_tone'].map(skin_tone_mapping)

print(f"\nDistribuzione skin_tone DOPO raggruppamento:")
df['skin_tone_grouped'].value_counts()

# label encoding
skin_tone_order = ['very_fair', 'light', 'medium', 'tan', 'deep', 'unknown']
df['skin_tone_encoded'] = df['skin_tone_grouped'].map({v:i for i,v in enumerate(skin_tone_order)})

print(f"\nDistribuzione skin_tone DOPO raggruppamento ed encoding:")
df['skin_tone_encoded'].value_counts()

# feature brand_name

df['brand_name'].nunique()

# recupero i 30 brand più frequenti
TOP_N = 30
top_brands = df['brand_name'].value_counts().nlargest(TOP_N).index

# creo la colonna
df['brand_top'] = df['brand_name'].where(
    df['brand_name'].isin(top_brands),
    'Other'
)

# verifica (31)
df['brand_top'].value_counts()

# frequency encoding: trasforma ogni valore di brand_name nel numero di volte che appare (brand_freq)
brand_freq = df['brand_name'].value_counts()
df['brand_freq'] = df['brand_name'].map(brand_freq)

# verifica
df[['brand_name', 'brand_freq']].head()

# label encoding
le_brand = LabelEncoder()
df['brand_top_encoded'] = le_brand.fit_transform(df['brand_top'])

# verifica
df['brand_top_encoded'].value_counts()

# feature categorie prodotti

df['primary_category'].nunique(), \
df['secondary_category'].nunique(), \
df['tertiary_category'].nunique()

# rimuovo primary_category dal set (ha una sola categoria)
df = df.drop(columns=['primary_category'])

# encoding secondary category
le_secondary = LabelEncoder()
df['secondary_category_encoded'] = le_secondary.fit_transform(df['secondary_category'])
df[['secondary_category', 'secondary_category_encoded']].head()

# encoding tertiary category
le_tertiary = LabelEncoder()
df['tertiary_category_encoded'] = le_tertiary.fit_transform(df['tertiary_category'])
df[['tertiary_category', 'tertiary_category_encoded']].head()

# check dataset

print(f"Shape: {df.shape}")
print(f"\nColonne:\n{df.columns.tolist()}")
print(f"\nPrime righe:")
print(df.head())

# salvo il dataset dopo gestione missing, trasformazioni ed encoding

df.to_csv("dataset_preprocessed2.csv", index=False)
files.download("dataset_preprocessed2.csv")

# SELEZIONE DELLE FEATURE PER LA BASELINE

# copia del dataset originale
df_baseline = df.copy()

columns_to_drop = [

    # originali già encoded
    'skin_tone',               # → skin_tone_encoded
    'skin_type',               # → skin_type_encoded
    'brand_name',              # → brand_freq + brand_top_encoded

    # intermedie
    'skin_tone_grouped',       # → skin_tone_encoded
    'brand_top',               # → brand_top_encoded

    # id tecnici
    'product_id',              # Non predittivo

    # originali trasformate
    'loves_count',             # → loves_count_log
    'reviews_count',           # → reviews_count_log

    # testuali
    'ingredients',
    'highlights',
]

df_baseline = df_baseline.drop(columns=columns_to_drop)

features_finali = [

    'is_recommended',

    'skin_type_encoded',
    'skin_tone_encoded',
    'review_price_usd',

    'brand_freq',           # frequenza brand
    'brand_top_encoded',    # top 30 brands encoded
    'secondary_category_encoded',
    'tertiary_category_encoded',
    'product_price_usd',
    'avg_product_rating',
    'loves_count_log',
    'reviews_count_log',
]

df_baseline = df_baseline[features_finali]

# check dataset
print(f"Shape: {df_baseline.shape}")
print(f"\nColonne:\n{df_baseline.columns.tolist()}")
print(f"\nPrime righe:")
print(df_baseline.head())

# salvo dataset pulito pronto per la baseline (prima dello split)

df_baseline.to_csv("dataset_baseline1.csv", index=False)
files.download("dataset_baseline1.csv")

# SPLIT

# separazione feature - target
X = df_baseline.drop(columns='is_recommended')
y = df_baseline['is_recommended']

# split train vs temp (70/30)
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

# split validation vs test (15/15)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

print("Train shape:", X_train.shape, y_train.shape)
print("Validation shape:", X_val.shape, y_val.shape)
print("Test shape:", X_test.shape, y_test.shape)

print("\nDistribuzione target:")
print("\nTrain:\n", y_train.value_counts(normalize=True))
print("\nValidation:\n", y_val.value_counts(normalize=True))
print("\nTest:\n", y_test.value_counts(normalize=True))

# SCALING VARIABILI NUMERICHE

numerical_features = [
    'review_price_usd',
    'brand_freq',
    'product_price_usd',
    'avg_product_rating',
    'loves_count_log',
    'reviews_count_log'
]

scaler = StandardScaler()

# fit su training set (solo colonne numeriche, no encodate)
X_train[numerical_features] = scaler.fit_transform(X_train[numerical_features])

# trasformo validation e test set con stesso scaler
X_val[numerical_features] = scaler.transform(X_val[numerical_features])
X_test[numerical_features] = scaler.transform(X_test[numerical_features])

# check
print("Train set scaled:")
print(X_train[numerical_features].describe().round(2))
print("\nValidation set scaled:")
print(X_val[numerical_features].describe().round(2))
print("\nTest set scaled:")
print(X_test[numerical_features].describe().round(2))

# salvo il dataset dopo split e scaling

# ricreo dataset completi con target
train = pd.concat([X_train, y_train], axis=1)
val   = pd.concat([X_val, y_val], axis=1)
test  = pd.concat([X_test, y_test], axis=1)

train.to_csv("train1.csv", index=False)
files.download("train1.csv")

val.to_csv("val1.csv", index=False)
files.download("val1.csv")

test.to_csv("test1.csv", index=False)
files.download("test1.csv")